server:
  port: 8080

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/brewedawakening
    username: user
    password: pwd
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.retry:
  instances:
    order:
      maxAttempts: 3
      waitDuration: 1000
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException
    rating:
      maxAttempts: 3
      waitDuration: 1000
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

---
spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:postgresql://postgres:5432/brewedawakening