server:
  port: 8081

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/brewedawakening
    username: isaimartinez
    password: $Wapoisai123
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true

---
spring.config.activate.on-profile: docker

spring.datasource.url: jdbc:postgresql://postgres:5432/brewedawakening
spring.datasource.username: user
spring.datasource.password: pwd