services:
  network-deploy-service:
    networks:
      - wapo

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.33.5.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none
      SPRING_PROFILES_ACTIVE: docker

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
