spring.config.import: "configserver:"

spring:
  application.name: gateway
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/brewed-awakening
          jwk-set-uri: http://localhost:7080/auth/realms/brewed-awakening/protocol/openid-connect/certs

management.metrics.tags.application: ${spring.application.name}

logging:
  level:
    root: info
    com:
      wapo: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

---

spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://configserver:8888