server.port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:${PWD}/config
#          searchLocations: file:///Users//isaimartinez//workspace//github.com//wapo-isai//brewed//brewedBackend//microservices//config

logging:
  level:
    root: info
---
spring.config.activate.on-profile: docker
spring.cloud.config.server.native.searchLocations: file:/config