spring.config.import: "configserver:"

spring:
  application.name: rating
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 20
    uri: http://localhost:8888

management.metrics.tags.application: ${spring.application.name}

logging:
  level:
    root: info
    com:
      wapo: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

---

spring.config.activate.on-profile: docker

spring.cloud.config.uri: http://configserver:8888